net:
  port: 27017
  bindIpAll: true
replication:
  replSetName: rs0
security:
  authorization: enabled
  keyFile: /etc/mongo-repl.key
#storage:
#  journal:
#    enabled: true #Default: true on 64-bit systems, false on 32-bit systems