version: "3.8"
services:
    broker_1:
      container_name: broker_1
      image: sw-nexus:9001/activemq-artemis-broker-1-dev-ops
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
          constraints: 
            - node.platform.os == linux
            - node.role == worker
            - node.tag == even
      ports:
        - "8161:8161" # Embedded web server
        - "61616:61616" # Main Artemis acceptor
      networks:
            artemis-cluster-network:
      environment:
        ANONYMOUS_LOGIN: "false"
        ARTEMIS_USERNAME: artemis 
        ARTEMIS_PASSWORD: 1234567890 
      volumes:
      - .:/var/lib/etc/
      - type: volume
        source: br_data
        target: /opt/messaging/artemis/data



    broker_2:
      container_name: broker_2
      image: sw-nexus:9001/activemq-artemis-broker-2-dev-ops
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
          constraints: 
            - node.platform.os == linux
      depends_on:
        - "broker_1"
      ports:
        - "8162:8161" # Embedded web server
        - "61617:61616" # Main Artemis acceptor
      networks:
        artemis-cluster-network:
      environment:
        ARTEMIS_USERNAME: artemis
        ARTEMIS_PASSWORD: 1234567890
      volumes:
      - .:/var/lib/etc/
      - type: volume
        source: br_data
        target: /opt/messaging/artemis/data



networks:
    artemis-cluster-network:
        driver: bridge
        attachable: true

volumes:
  br_data:
        driver: local
        driver_opts:
          o: bind
          type: none
          device: /opt/docker/broker/data  
