version: '3.8'
services:

  mongodb1:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == mongo
      resources:
        limits:
          cpus: '0.90'
          memory: 3G
        reservations:
          cpus: '0.90'
          memory: 3G
    ports:
      - 30001:27017
    networks:
      - alphanetwork
    volumes:
      - data1:/data/db
      - config1:/data/configdb
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongodb2:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == mongo
      resources:
        limits:
          cpus: '0.90'
          memory: 3G
        reservations:
          cpus: '0.90'
          memory: 3G
    ports:
      - 30002:27017
    networks:
      - alphanetwork
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongodb3:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == mongo
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 30003:27017
    networks:
      - alphanetwork
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongoclient:
    image: sw-nexus:9001/mongo5_client:1.0.0
    deploy:
      replicas: 1
      restart_policy :
        condition: none
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == mongo
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - alphanetwork
    entrypoint: ["/deployment_scripts/", "initiate_replica.sh"]
#    volumes:
#      - ./deployment_scripts:/deployment_scripts
    command: ./deployment_scripts/initiate_replica.sh

networks:
  alphanetwork:
    driver: overlay
    attachable: true

volumes:
  data1:
  config1: