version: '3.8'
services:

  mongodb1:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == Swarm-Mongo1-Prd
      resources:
        limits:
          cpus: '0.90'
          memory: 3G
        reservations:
          cpus: '0.90'
          memory: 3G
    ports:
      - 30001:27017
    networks:
      - alphanetwork
    volumes:
      - type: volume
        source: mongodb1_data
        target: /data/db/
      - type: volume
        source: mongodb1_configdb
        target: /data/config/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongodb2:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == Swarm-Mongo2-Prd
      resources:
        limits:
          cpus: '0.90'
          memory: 3G
        reservations:
          cpus: '0.90'
          memory: 3G
    ports:
      - 30002:27017
    networks:
      - alphanetwork
    volumes:
      - type: volume
        source: mongodb2_data
        target: /data/db/
      - type: volume
        source: mongodb2_configdb
        target: /data/config/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongodb3:
    image: mongo:5
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == Swarm-Mongo-Arb-Prd
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 30003:27017
    networks:
      - alphanetwork
    volumes:
      - type: volume
        source: mongodb_arb_data
        target: /data/db/
      - type: volume
        source: mongodb_arb_configdb
        target: /data/config/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongoclient:
    image: sw-nexus:9001/mongo5_client:1.0.0
    deploy:
      replicas: 1
      restart_policy :
        condition: none
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
          - node.labels.type == Swarm-Mongo-Arb-Prd
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - alphanetwork

networks:
  alphanetwork:
    driver: overlay
    attachable: true

volumes:
  mongodb1_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/mongodb1/data/db/

  mongodb1_configdb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/mongodb1/data/configdb/

  mongodb2_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/mongodb2/data/db/

  mongodb2_configdb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/mongodb2/data/configdb/

  mongodb_arb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/arbiter/data/db/

  mongodb_arb_configdb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker-volumes/nfs/mongo5/arbiter/data/configdb/