version: '3.8'
services:

  haproxy:
    image: haproxy:2.7
    restart: on-failure
    ports:
      - 40001:40001
      - 40002:40002
      - 40003:40003
#      Add more ports for load balancing
    volumes:
#      save  haproxy.cfg at /opt/haproxy/ host machine, in case of multiple workers, nfs must be implemented.
      - /opt/haproxy/:/usr/local/etc/haproxy/:ro
